services:
  admin-panel:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: admin-panel-dev
    networks:
      - web-network
    volumes:
      - .:/app
      - admin-node-modules:/app/node_modules
      - .next:/app/.next
    env_file:
      - .env
    environment:
      NODE_ENV: development

volumes:
  admin-node-modules:

networks:
  web-network:
    external: true